export const ACCESS_CREATE_REQUEST = 'ACCESS_CREATE_REQUEST'
export const ACCESS_CREATE_SUCCESS = 'ACCESS_CREATE_SUCCESS'
export const ACCESS_CREATE_FAIL = 'ACCESS_CREATE_FAIL'

export const ACCESS_LIST_REQUEST = 'ACCESS_LIST_REQUEST'
export const ACCESS_LIST_SUCCESS = 'ACCESS_LIST_SUCCESS'
export const ACCESS_LIST_FAIL = 'ACCESS_LIST_FAIL'
